//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Seguridad {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Seguridad() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Seguridad", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 236.
        /// </summary>
        internal static string ABMdeActas {
            get {
                return ResourceManager.GetString("ABMdeActas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 118.
        /// </summary>
        internal static string ABMdeExpedientesdeObra {
            get {
                return ResourceManager.GetString("ABMdeExpedientesdeObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 244.
        /// </summary>
        internal static string ABMdePersonas {
            get {
                return ResourceManager.GetString("ABMdePersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 262.
        /// </summary>
        internal static string ABMDocumentos {
            get {
                return ResourceManager.GetString("ABMDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120.
        /// </summary>
        internal static string ABMDomicilios {
            get {
                return ResourceManager.GetString("ABMDomicilios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 282.
        /// </summary>
        internal static string ABMPersonas {
            get {
                return ResourceManager.GetString("ABMPersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 257.
        /// </summary>
        internal static string ABMProfesion {
            get {
                return ResourceManager.GetString("ABMProfesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 129.
        /// </summary>
        internal static string AccederalMantenedorparcelario {
            get {
                return ResourceManager.GetString("AccederalMantenedorparcelario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 119.
        /// </summary>
        internal static string Actas {
            get {
                return ResourceManager.GetString("Actas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 347.
        /// </summary>
        internal static string ActualizacionObjetoAdministrativo {
            get {
                return ResourceManager.GetString("ActualizacionObjetoAdministrativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 338.
        /// </summary>
        internal static string ActualizacionPadrones {
            get {
                return ResourceManager.GetString("ActualizacionPadrones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 617.
        /// </summary>
        internal static string AdministracionDDJJ {
            get {
                return ResourceManager.GetString("AdministracionDDJJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 47.
        /// </summary>
        internal static string AdministraciondeFeriados {
            get {
                return ResourceManager.GetString("AdministraciondeFeriados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 43.
        /// </summary>
        internal static string AdministraciondeHorarios {
            get {
                return ResourceManager.GetString("AdministraciondeHorarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 39.
        /// </summary>
        internal static string AdministraciondePerfiles {
            get {
                return ResourceManager.GetString("AdministraciondePerfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 51.
        /// </summary>
        internal static string AdministraciondeTablasAuxiliares {
            get {
                return ResourceManager.GetString("AdministraciondeTablasAuxiliares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35.
        /// </summary>
        internal static string AdministraciondeUsuarios {
            get {
                return ResourceManager.GetString("AdministraciondeUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 602.
        /// </summary>
        internal static string AdministracionValuacion {
            get {
                return ResourceManager.GetString("AdministracionValuacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17.
        /// </summary>
        internal static string AgregarControlesTecnicos {
            get {
                return ResourceManager.GetString("AgregarControlesTecnicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string AgregarExpedienteObra {
            get {
                return ResourceManager.GetString("AgregarExpedienteObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48.
        /// </summary>
        internal static string AgregarFeriados {
            get {
                return ResourceManager.GetString("AgregarFeriados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string AgregarLiquidaciones {
            get {
                return ResourceManager.GetString("AgregarLiquidaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string AgregarObservaciones {
            get {
                return ResourceManager.GetString("AgregarObservaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string AgregarPlanos {
            get {
                return ResourceManager.GetString("AgregarPlanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        internal static string AgregarSuperficies {
            get {
                return ResourceManager.GetString("AgregarSuperficies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 52.
        /// </summary>
        internal static string AgregarTablasAux {
            get {
                return ResourceManager.GetString("AgregarTablasAux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 105.
        /// </summary>
        internal static string AltaAlfanumericodeParcelasyPosesiones {
            get {
                return ResourceManager.GetString("AltaAlfanumericodeParcelasyPosesiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 195.
        /// </summary>
        internal static string AltaAtributo {
            get {
                return ResourceManager.GetString("AltaAtributo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 213.
        /// </summary>
        internal static string AltaCertificados {
            get {
                return ResourceManager.GetString("AltaCertificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 182.
        /// </summary>
        internal static string AltaControlTecnico {
            get {
                return ResourceManager.GetString("AltaControlTecnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 239.
        /// </summary>
        internal static string AltadeActas {
            get {
                return ResourceManager.GetString("AltadeActas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 252.
        /// </summary>
        internal static string AltadeDomicilio {
            get {
                return ResourceManager.GetString("AltadeDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 227.
        /// </summary>
        internal static string AltadeInspeccion {
            get {
                return ResourceManager.GetString("AltadeInspeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 231.
        /// </summary>
        internal static string Altadeinspectores {
            get {
                return ResourceManager.GetString("Altadeinspectores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123.
        /// </summary>
        internal static string AltadeParcelasDestino {
            get {
                return ResourceManager.GetString("AltadeParcelasDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 122.
        /// </summary>
        internal static string AltadeParcelasOrigen {
            get {
                return ResourceManager.GetString("AltadeParcelasOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 246.
        /// </summary>
        internal static string AltadePersonas {
            get {
                return ResourceManager.GetString("AltadePersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 259.
        /// </summary>
        internal static string AltadeProfesion {
            get {
                return ResourceManager.GetString("AltadeProfesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 269.
        /// </summary>
        internal static string Altaderegistros {
            get {
                return ResourceManager.GetString("Altaderegistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 202.
        /// </summary>
        internal static string AltadeResultadodeBusqueda {
            get {
                return ResourceManager.GetString("AltadeResultadodeBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 497.
        /// </summary>
        internal static string AltaDesignaciones {
            get {
                return ResourceManager.GetString("AltaDesignaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 218.
        /// </summary>
        internal static string AltadeTramites {
            get {
                return ResourceManager.GetString("AltadeTramites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 172.
        /// </summary>
        internal static string AltaDocumento {
            get {
                return ResourceManager.GetString("AltaDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 620.
        /// </summary>
        internal static string AltaDocumentoMensura {
            get {
                return ResourceManager.GetString("AltaDocumentoMensura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 136.
        /// </summary>
        internal static string AltaDocumentosParcela {
            get {
                return ResourceManager.GetString("AltaDocumentosParcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 149.
        /// </summary>
        internal static string AltaDocumentosUnidadTributaria {
            get {
                return ResourceManager.GetString("AltaDocumentosUnidadTributaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 142.
        /// </summary>
        internal static string AltaDomicilio {
            get {
                return ResourceManager.GetString("AltaDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 152.
        /// </summary>
        internal static string AltaDominio {
            get {
                return ResourceManager.GetString("AltaDominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 166.
        /// </summary>
        internal static string AltaEstado {
            get {
                return ResourceManager.GetString("AltaEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 158.
        /// </summary>
        internal static string AltaExpedientesObra {
            get {
                return ResourceManager.GetString("AltaExpedientesObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 44.
        /// </summary>
        internal static string AltaHorario {
            get {
                return ResourceManager.GetString("AltaHorario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 181.
        /// </summary>
        internal static string AltaInspeccion {
            get {
                return ResourceManager.GetString("AltaInspeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 178.
        /// </summary>
        internal static string AltaLiquidacion {
            get {
                return ResourceManager.GetString("AltaLiquidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 312.
        /// </summary>
        internal static string AltaMantenedorUnidadTributaria {
            get {
                return ResourceManager.GetString("AltaMantenedorUnidadTributaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 607.
        /// </summary>
        internal static string AltaMensura {
            get {
                return ResourceManager.GetString("AltaMensura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 133.
        /// </summary>
        internal static string AltaNomenclatura {
            get {
                return ResourceManager.GetString("AltaNomenclatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 185.
        /// </summary>
        internal static string AltaObservacion {
            get {
                return ResourceManager.GetString("AltaObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 610.
        /// </summary>
        internal static string AltaParcelasMensura {
            get {
                return ResourceManager.GetString("AltaParcelasMensura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40.
        /// </summary>
        internal static string AltaPerfil {
            get {
                return ResourceManager.GetString("AltaPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 175.
        /// </summary>
        internal static string AltaPersona {
            get {
                return ResourceManager.GetString("AltaPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 145.
        /// </summary>
        internal static string AltaResponsableFiscal {
            get {
                return ResourceManager.GetString("AltaResponsableFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 168.
        /// </summary>
        internal static string AltaSuperficie {
            get {
                return ResourceManager.GetString("AltaSuperficie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 155.
        /// </summary>
        internal static string AltaTitular {
            get {
                return ResourceManager.GetString("AltaTitular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 163.
        /// </summary>
        internal static string AltaUbicacionObra {
            get {
                return ResourceManager.GetString("AltaUbicacionObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 161.
        /// </summary>
        internal static string AltaUnidadesTributarias {
            get {
                return ResourceManager.GetString("AltaUnidadesTributarias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 36.
        /// </summary>
        internal static string AltaUsuario {
            get {
                return ResourceManager.GetString("AltaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 250.
        /// </summary>
        internal static string AMBDomicilio {
            get {
                return ResourceManager.GetString("AMBDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 112.
        /// </summary>
        internal static string AsociaciondeParcelasGraficasyAlfanumericas {
            get {
                return ResourceManager.GetString("AsociaciondeParcelasGraficasyAlfanumericas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 102.
        /// </summary>
        internal static string Auditoria {
            get {
                return ResourceManager.GetString("Auditoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 215.
        /// </summary>
        internal static string BajaCertificados {
            get {
                return ResourceManager.GetString("BajaCertificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 183.
        /// </summary>
        internal static string BajaControlTecnico {
            get {
                return ResourceManager.GetString("BajaControlTecnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 241.
        /// </summary>
        internal static string Bajadeactas {
            get {
                return ResourceManager.GetString("Bajadeactas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 197.
        /// </summary>
        internal static string BajadeAtributos {
            get {
                return ResourceManager.GetString("BajadeAtributos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 254.
        /// </summary>
        internal static string BajadeDomicilio {
            get {
                return ResourceManager.GetString("BajadeDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 229.
        /// </summary>
        internal static string BajadeInspeccion {
            get {
                return ResourceManager.GetString("BajadeInspeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 232.
        /// </summary>
        internal static string Bajadeinspectores {
            get {
                return ResourceManager.GetString("Bajadeinspectores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 177.
        /// </summary>
        internal static string BajadeLiquidacion {
            get {
                return ResourceManager.GetString("BajadeLiquidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 125.
        /// </summary>
        internal static string BajadeParcelasDestino {
            get {
                return ResourceManager.GetString("BajadeParcelasDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 124.
        /// </summary>
        internal static string BajadeParcelasOrigen {
            get {
                return ResourceManager.GetString("BajadeParcelasOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 248.
        /// </summary>
        internal static string BajadePersonas {
            get {
                return ResourceManager.GetString("BajadePersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 478.
        /// </summary>
        internal static string BajadePlantilla {
            get {
                return ResourceManager.GetString("BajadePlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 261.
        /// </summary>
        internal static string BajadeProfesion {
            get {
                return ResourceManager.GetString("BajadeProfesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 271.
        /// </summary>
        internal static string BajadeRegistros {
            get {
                return ResourceManager.GetString("BajadeRegistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 204.
        /// </summary>
        internal static string BajadeResultadodeBusqueda {
            get {
                return ResourceManager.GetString("BajadeResultadodeBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 498.
        /// </summary>
        internal static string BajaDesignaciones {
            get {
                return ResourceManager.GetString("BajaDesignaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 220.
        /// </summary>
        internal static string BajadeTramite {
            get {
                return ResourceManager.GetString("BajadeTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 173.
        /// </summary>
        internal static string BajaDocumento {
            get {
                return ResourceManager.GetString("BajaDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 621.
        /// </summary>
        internal static string BajaDocumentoMesnsura {
            get {
                return ResourceManager.GetString("BajaDocumentoMesnsura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 138.
        /// </summary>
        internal static string BajaDocumentosParcela {
            get {
                return ResourceManager.GetString("BajaDocumentosParcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 151.
        /// </summary>
        internal static string BajaDocumentosUnidadTributaria {
            get {
                return ResourceManager.GetString("BajaDocumentosUnidadTributaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 144.
        /// </summary>
        internal static string BajaDomicilio {
            get {
                return ResourceManager.GetString("BajaDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 154.
        /// </summary>
        internal static string BajaDominio {
            get {
                return ResourceManager.GetString("BajaDominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 189.
        /// </summary>
        internal static string BajaExpedientedeObra {
            get {
                return ResourceManager.GetString("BajaExpedientedeObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 159.
        /// </summary>
        internal static string BajaExpedientesObra {
            get {
                return ResourceManager.GetString("BajaExpedientesObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 179.
        /// </summary>
        internal static string BajaLiquidacion {
            get {
                return ResourceManager.GetString("BajaLiquidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 313.
        /// </summary>
        internal static string BajaMantenedorUnidadTributaria {
            get {
                return ResourceManager.GetString("BajaMantenedorUnidadTributaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 609.
        /// </summary>
        internal static string BajaMensura {
            get {
                return ResourceManager.GetString("BajaMensura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 135.
        /// </summary>
        internal static string BajaNomenclatura {
            get {
                return ResourceManager.GetString("BajaNomenclatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 186.
        /// </summary>
        internal static string BajaObservacion {
            get {
                return ResourceManager.GetString("BajaObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 176.
        /// </summary>
        internal static string BajaPersona {
            get {
                return ResourceManager.GetString("BajaPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 147.
        /// </summary>
        internal static string BajaResponsableFiscal {
            get {
                return ResourceManager.GetString("BajaResponsableFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 169.
        /// </summary>
        internal static string BajaSuperficie {
            get {
                return ResourceManager.GetString("BajaSuperficie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 157.
        /// </summary>
        internal static string BajaTitular {
            get {
                return ResourceManager.GetString("BajaTitular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 164.
        /// </summary>
        internal static string BajaUbicacionObra {
            get {
                return ResourceManager.GetString("BajaUbicacionObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 162.
        /// </summary>
        internal static string BajaUnidadesTributarias {
            get {
                return ResourceManager.GetString("BajaUnidadesTributarias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 201.
        /// </summary>
        internal static string BusquedAlfanumericadeobjetosdeInfraestructura {
            get {
                return ResourceManager.GetString("BusquedAlfanumericadeobjetosdeInfraestructura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 327.
        /// </summary>
        internal static string Catastro {
            get {
                return ResourceManager.GetString("Catastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 336.
        /// </summary>
        internal static string CatastroProvincial {
            get {
                return ResourceManager.GetString("CatastroProvincial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 495.
        /// </summary>
        internal static string CertificadoCatastral {
            get {
                return ResourceManager.GetString("CertificadoCatastral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 210.
        /// </summary>
        internal static string Certificados {
            get {
                return ResourceManager.GetString("Certificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 603.
        /// </summary>
        internal static string CertificadoValuatorio {
            get {
                return ResourceManager.GetString("CertificadoValuatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 284.
        /// </summary>
        internal static string ConexionCAD {
            get {
                return ResourceManager.GetString("ConexionCAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 330.
        /// </summary>
        internal static string Configuracion {
            get {
                return ResourceManager.GetString("Configuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 216.
        /// </summary>
        internal static string ConfiguraciondeCertificados {
            get {
                return ResourceManager.GetString("ConfiguraciondeCertificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33.
        /// </summary>
        internal static string ConfiguraciondeParametrosGenerales {
            get {
                return ResourceManager.GetString("ConfiguraciondeParametrosGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101.
        /// </summary>
        internal static string Consulta {
            get {
                return ResourceManager.GetString("Consulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 333.
        /// </summary>
        internal static string ConsultadelPadron {
            get {
                return ResourceManager.GetString("ConsultadelPadron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 283.
        /// </summary>
        internal static string ConsultadeTramites {
            get {
                return ResourceManager.GetString("ConsultadeTramites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 320.
        /// </summary>
        internal static string ConsultarEstadoDeuda {
            get {
                return ResourceManager.GetString("ConsultarEstadoDeuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 601.
        /// </summary>
        internal static string DeclaracionesJuradas {
            get {
                return ResourceManager.GetString("DeclaracionesJuradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 476.
        /// </summary>
        internal static string DespublicarPlantilla {
            get {
                return ResourceManager.GetString("DespublicarPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 321.
        /// </summary>
        internal static string EditarValuacion {
            get {
                return ResourceManager.GetString("EditarValuacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 352.
        /// </summary>
        internal static string EliminarBibliotecaBA {
            get {
                return ResourceManager.GetString("EliminarBibliotecaBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 349.
        /// </summary>
        internal static string EliminarBibliotecaMT {
            get {
                return ResourceManager.GetString("EliminarBibliotecaMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19.
        /// </summary>
        internal static string EliminarControlesTecnicos {
            get {
                return ResourceManager.GetString("EliminarControlesTecnicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string EliminarExpedienteObra {
            get {
                return ResourceManager.GetString("EliminarExpedienteObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        internal static string EliminarFeriados {
            get {
                return ResourceManager.GetString("EliminarFeriados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 46.
        /// </summary>
        internal static string EliminarHorario {
            get {
                return ResourceManager.GetString("EliminarHorario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 117.
        /// </summary>
        internal static string EliminarInspectores {
            get {
                return ResourceManager.GetString("EliminarInspectores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string EliminarLiquidaciones {
            get {
                return ResourceManager.GetString("EliminarLiquidaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        internal static string EliminarObservaciones {
            get {
                return ResourceManager.GetString("EliminarObservaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 111.
        /// </summary>
        internal static string EliminarParcelaDestino {
            get {
                return ResourceManager.GetString("EliminarParcelaDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 108.
        /// </summary>
        internal static string EliminarParcelaOrigen {
            get {
                return ResourceManager.GetString("EliminarParcelaOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 42.
        /// </summary>
        internal static string EliminarPerfil {
            get {
                return ResourceManager.GetString("EliminarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string EliminarPlanos {
            get {
                return ResourceManager.GetString("EliminarPlanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26.
        /// </summary>
        internal static string EliminarSuperficies {
            get {
                return ResourceManager.GetString("EliminarSuperficies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 54.
        /// </summary>
        internal static string EliminarTablaAux {
            get {
                return ResourceManager.GetString("EliminarTablaAux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38.
        /// </summary>
        internal static string EliminarUsuarios {
            get {
                return ResourceManager.GetString("EliminarUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string ExpedientedeObra {
            get {
                return ResourceManager.GetString("ExpedientedeObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 324.
        /// </summary>
        internal static string ExportarCADAdmin {
            get {
                return ResourceManager.GetString("ExportarCADAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 325.
        /// </summary>
        internal static string ExportarCADUsuario {
            get {
                return ResourceManager.GetString("ExportarCADUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 211.
        /// </summary>
        internal static string GeneraciondeCertificados {
            get {
                return ResourceManager.GetString("GeneraciondeCertificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 209.
        /// </summary>
        internal static string GeneraciondeReportes {
            get {
                return ResourceManager.GetString("GeneraciondeReportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 104.
        /// </summary>
        internal static string Generarauditoria {
            get {
                return ResourceManager.GetString("Generarauditoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 198.
        /// </summary>
        internal static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 234.
        /// </summary>
        internal static string Guardarcambios {
            get {
                return ResourceManager.GetString("Guardarcambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 266.
        /// </summary>
        internal static string GuardarDocumentos {
            get {
                return ResourceManager.GetString("GuardarDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 255.
        /// </summary>
        internal static string GuardarDomicilio {
            get {
                return ResourceManager.GetString("GuardarDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 126.
        /// </summary>
        internal static string GuardarGeneral {
            get {
                return ResourceManager.GetString("GuardarGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 249.
        /// </summary>
        internal static string GuardarPersona {
            get {
                return ResourceManager.GetString("GuardarPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 272.
        /// </summary>
        internal static string Guardarregistros {
            get {
                return ResourceManager.GetString("Guardarregistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 243.
        /// </summary>
        internal static string Herramientas {
            get {
                return ResourceManager.GetString("Herramientas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 237.
        /// </summary>
        internal static string InformedeActaVencidasporPlazosOtorgados {
            get {
                return ResourceManager.GetString("InformedeActaVencidasporPlazosOtorgados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 199.
        /// </summary>
        internal static string InformedeAtributoporZona {
            get {
                return ResourceManager.GetString("InformedeAtributoporZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 224.
        /// </summary>
        internal static string InformedeInspeccionesporPeriodo {
            get {
                return ResourceManager.GetString("InformedeInspeccionesporPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 225.
        /// </summary>
        internal static string InformedeInspeccionesporTipodeInspeccion {
            get {
                return ResourceManager.GetString("InformedeInspeccionesporTipodeInspeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 206.
        /// </summary>
        internal static string InformedeObjetodeInfraestructura {
            get {
                return ResourceManager.GetString("InformedeObjetodeInfraestructura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 113.
        /// </summary>
        internal static string InformedeSeguimientodeExpedientesdeO {
            get {
                return ResourceManager.GetString("InformedeSeguimientodeExpedientesdeO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        internal static string InformedeSeguimientodeExpedientesdeObra {
            get {
                return ResourceManager.GetString("InformedeSeguimientodeExpedientesdeObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string InformeEstadisticodeEdificacion {
            get {
                return ResourceManager.GetString("InformeEstadisticodeEdificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 311.
        /// </summary>
        internal static string InformeParcelario {
            get {
                return ResourceManager.GetString("InformeParcelario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 208.
        /// </summary>
        internal static string Informes {
            get {
                return ResourceManager.GetString("Informes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 316.
        /// </summary>
        internal static string InformeTributario {
            get {
                return ResourceManager.GetString("InformeTributario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 116.
        /// </summary>
        internal static string InsertarInspectores {
            get {
                return ResourceManager.GetString("InsertarInspectores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 110.
        /// </summary>
        internal static string InsertarParcelaDestino {
            get {
                return ResourceManager.GetString("InsertarParcelaDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 107.
        /// </summary>
        internal static string InsertarParcelaOrigen {
            get {
                return ResourceManager.GetString("InsertarParcelaOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 115.
        /// </summary>
        internal static string Inspecciones {
            get {
                return ResourceManager.GetString("Inspecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 334.
        /// </summary>
        internal static string InspeccionesSubmenu {
            get {
                return ResourceManager.GetString("InspeccionesSubmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 274.
        /// </summary>
        internal static string Instructivo {
            get {
                return ResourceManager.GetString("Instructivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 345.
        /// </summary>
        internal static string IntercambioCADconGeRED {
            get {
                return ResourceManager.GetString("IntercambioCADconGeRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 335.
        /// </summary>
        internal static string Interfaces {
            get {
                return ResourceManager.GetString("Interfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 275.
        /// </summary>
        internal static string LinksaOtrosSitiosdeInteres {
            get {
                return ResourceManager.GetString("LinksaOtrosSitiosdeInteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 276.
        /// </summary>
        internal static string Listadodetareasporusuarios {
            get {
                return ResourceManager.GetString("Listadodetareasporusuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 278.
        /// </summary>
        internal static string ListadodeUsuariosportareas {
            get {
                return ResourceManager.GetString("ListadodeUsuariosportareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 326.
        /// </summary>
        internal static string Loginexitoso {
            get {
                return ResourceManager.GetString("Loginexitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 114.
        /// </summary>
        internal static string MantenedorParcelario {
            get {
                return ResourceManager.GetString("MantenedorParcelario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 328.
        /// </summary>
        internal static string MantenimientodeAtributosysusValoresporZona {
            get {
                return ResourceManager.GetString("MantenimientodeAtributosysusValoresporZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 273.
        /// </summary>
        internal static string MantenimientodeCalles {
            get {
                return ResourceManager.GetString("MantenimientodeCalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        internal static string MantenimientodeDatosdeInfraestructura {
            get {
                return ResourceManager.GetString("MantenimientodeDatosdeInfraestructura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 193.
        /// </summary>
        internal static string MantenimientodelCodigodePlaneamientoUrbano {
            get {
                return ResourceManager.GetString("MantenimientodelCodigodePlaneamientoUrbano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 329.
        /// </summary>
        internal static string MantenimientodeObjetosdeInfraestructura {
            get {
                return ResourceManager.GetString("MantenimientodeObjetosdeInfraestructura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 267.
        /// </summary>
        internal static string MantenimientodeTablasAuxiliares {
            get {
                return ResourceManager.GetString("MantenimientodeTablasAuxiliares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 205.
        /// </summary>
        internal static string MapaderesultadodeBusqueda {
            get {
                return ResourceManager.GetString("MapaderesultadodeBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 253.
        /// </summary>
        internal static string ModifiarDomicilio {
            get {
                return ResourceManager.GetString("ModifiarDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 240.
        /// </summary>
        internal static string ModificaciondeActas {
            get {
                return ResourceManager.GetString("ModificaciondeActas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 196.
        /// </summary>
        internal static string ModificaciondeAtributos {
            get {
                return ResourceManager.GetString("ModificaciondeAtributos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 203.
        /// </summary>
        internal static string ModificaciondeResultadodeBusqueda {
            get {
                return ResourceManager.GetString("ModificaciondeResultadodeBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 160.
        /// </summary>
        internal static string ModificacionExpedientesObra {
            get {
                return ResourceManager.GetString("ModificacionExpedientesObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 608.
        /// </summary>
        internal static string ModificacionMensura {
            get {
                return ResourceManager.GetString("ModificacionMensura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 214.
        /// </summary>
        internal static string ModificarCertificados {
            get {
                return ResourceManager.GetString("ModificarCertificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.
        /// </summary>
        internal static string ModificarControlesTecnicos {
            get {
                return ResourceManager.GetString("ModificarControlesTecnicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 184.
        /// </summary>
        internal static string ModificarControlTecnico {
            get {
                return ResourceManager.GetString("ModificarControlTecnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 499.
        /// </summary>
        internal static string ModificarDesignaciones {
            get {
                return ResourceManager.GetString("ModificarDesignaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 174.
        /// </summary>
        internal static string ModificarDocumento {
            get {
                return ResourceManager.GetString("ModificarDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 622.
        /// </summary>
        internal static string ModificarDocumentoMensura {
            get {
                return ResourceManager.GetString("ModificarDocumentoMensura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 137.
        /// </summary>
        internal static string ModificarDocumentosParcela {
            get {
                return ResourceManager.GetString("ModificarDocumentosParcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150.
        /// </summary>
        internal static string ModificarDocumentosUnidadTributaria {
            get {
                return ResourceManager.GetString("ModificarDocumentosUnidadTributaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 143.
        /// </summary>
        internal static string ModificarDomicilio {
            get {
                return ResourceManager.GetString("ModificarDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 153.
        /// </summary>
        internal static string ModificarDominio {
            get {
                return ResourceManager.GetString("ModificarDominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 167.
        /// </summary>
        internal static string ModificarEstado {
            get {
                return ResourceManager.GetString("ModificarEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string ModificarExpedienteObra {
            get {
                return ResourceManager.GetString("ModificarExpedienteObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 49.
        /// </summary>
        internal static string ModificarFeriados {
            get {
                return ResourceManager.GetString("ModificarFeriados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45.
        /// </summary>
        internal static string ModificarHorarios {
            get {
                return ResourceManager.GetString("ModificarHorarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 228.
        /// </summary>
        internal static string ModificarInspeccion {
            get {
                return ResourceManager.GetString("ModificarInspeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 233.
        /// </summary>
        internal static string Modificarinspectores {
            get {
                return ResourceManager.GetString("Modificarinspectores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180.
        /// </summary>
        internal static string ModificarLiquidacion {
            get {
                return ResourceManager.GetString("ModificarLiquidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string ModificarLiquidaciones {
            get {
                return ResourceManager.GetString("ModificarLiquidaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 130.
        /// </summary>
        internal static string ModificarMantenedorParcelario {
            get {
                return ResourceManager.GetString("ModificarMantenedorParcelario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 314.
        /// </summary>
        internal static string ModificarMantenedorUnidadTributaria {
            get {
                return ResourceManager.GetString("ModificarMantenedorUnidadTributaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 134.
        /// </summary>
        internal static string ModificarNomenclatura {
            get {
                return ResourceManager.GetString("ModificarNomenclatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 188.
        /// </summary>
        internal static string ModificarObservacion {
            get {
                return ResourceManager.GetString("ModificarObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        internal static string ModificarObservaciones {
            get {
                return ResourceManager.GetString("ModificarObservaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 34.
        /// </summary>
        internal static string ModificarParametrosGenerales {
            get {
                return ResourceManager.GetString("ModificarParametrosGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41.
        /// </summary>
        internal static string ModificarPerfil {
            get {
                return ResourceManager.GetString("ModificarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 247.
        /// </summary>
        internal static string ModificarPersonas {
            get {
                return ResourceManager.GetString("ModificarPersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string ModificarPlanos {
            get {
                return ResourceManager.GetString("ModificarPlanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 477.
        /// </summary>
        internal static string ModificarPlantilla {
            get {
                return ResourceManager.GetString("ModificarPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 260.
        /// </summary>
        internal static string ModificarProfesion {
            get {
                return ResourceManager.GetString("ModificarProfesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 270.
        /// </summary>
        internal static string ModificarRegistreos {
            get {
                return ResourceManager.GetString("ModificarRegistreos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 146.
        /// </summary>
        internal static string ModificarResponsableFiscal {
            get {
                return ResourceManager.GetString("ModificarResponsableFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 171.
        /// </summary>
        internal static string ModificarSuperficie {
            get {
                return ResourceManager.GetString("ModificarSuperficie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        internal static string ModificarSuperficies {
            get {
                return ResourceManager.GetString("ModificarSuperficies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 623.
        /// </summary>
        internal static string ModificarSuperficieVigencia {
            get {
                return ResourceManager.GetString("ModificarSuperficieVigencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 53.
        /// </summary>
        internal static string ModificarTablasAux {
            get {
                return ResourceManager.GetString("ModificarTablasAux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 156.
        /// </summary>
        internal static string ModificarTitular {
            get {
                return ResourceManager.GetString("ModificarTitular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 219.
        /// </summary>
        internal static string ModificarTramites {
            get {
                return ResourceManager.GetString("ModificarTramites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 37.
        /// </summary>
        internal static string ModificarUsuarios {
            get {
                return ResourceManager.GetString("ModificarUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32.
        /// </summary>
        internal static string ModuloSeguridad {
            get {
                return ResourceManager.GetString("ModuloSeguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 520.
        /// </summary>
        internal static string MPAltaParcelasOrigen {
            get {
                return ResourceManager.GetString("MPAltaParcelasOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 521.
        /// </summary>
        internal static string MPBajaParcelasOrigen {
            get {
                return ResourceManager.GetString("MPBajaParcelasOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 522.
        /// </summary>
        internal static string MPModificacionParcelasOrigen {
            get {
                return ResourceManager.GetString("MPModificacionParcelasOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string ObrasParticulares {
            get {
                return ResourceManager.GetString("ObrasParticulares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 619.
        /// </summary>
        internal static string PermiteDDJJSoRNoVigentes {
            get {
                return ResourceManager.GetString("PermiteDDJJSoRNoVigentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 192.
        /// </summary>
        internal static string Planeamiento {
            get {
                return ResourceManager.GetString("Planeamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 221.
        /// </summary>
        internal static string Planificarinspecciones {
            get {
                return ResourceManager.GetString("Planificarinspecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 165.
        /// </summary>
        internal static string PrimarioUbicacionObra {
            get {
                return ResourceManager.GetString("PrimarioUbicacionObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 350.
        /// </summary>
        internal static string PublicarDespublicarBibliotecaBA {
            get {
                return ResourceManager.GetString("PublicarDespublicarBibliotecaBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 349.
        /// </summary>
        internal static string PublicarDespublicarBibliotecaMT {
            get {
                return ResourceManager.GetString("PublicarDespublicarBibliotecaMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 475.
        /// </summary>
        internal static string PublicarPlantilla {
            get {
                return ResourceManager.GetString("PublicarPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 264.
        /// </summary>
        internal static string QuitarDocumentos {
            get {
                return ResourceManager.GetString("QuitarDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 277.
        /// </summary>
        internal static string Rankingdetareasporusuarios {
            get {
                return ResourceManager.GetString("Rankingdetareasporusuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 279.
        /// </summary>
        internal static string RankingdeUusariosportareas {
            get {
                return ResourceManager.GetString("RankingdeUusariosportareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 280.
        /// </summary>
        internal static string RankingGeneraldetareas {
            get {
                return ResourceManager.GetString("RankingGeneraldetareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 103.
        /// </summary>
        internal static string RankingGeneraldetiposdeobjetosyCantidad {
            get {
                return ResourceManager.GetString("RankingGeneraldetiposdeobjetosyCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 127.
        /// </summary>
        internal static string RealizarAsosicion {
            get {
                return ResourceManager.GetString("RealizarAsosicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 128.
        /// </summary>
        internal static string RealizarDesasociacion {
            get {
                return ResourceManager.GetString("RealizarDesasociacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 518.
        /// </summary>
        internal static string ReasignacionTramites {
            get {
                return ResourceManager.GetString("ReasignacionTramites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 223.
        /// </summary>
        internal static string RegistrodeInspectores {
            get {
                return ResourceManager.GetString("RegistrodeInspectores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 337.
        /// </summary>
        internal static string Rentas {
            get {
                return ResourceManager.GetString("Rentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 222.
        /// </summary>
        internal static string TablerodeInspecciones {
            get {
                return ResourceManager.GetString("TablerodeInspecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 207.
        /// </summary>
        internal static string Valuacion {
            get {
                return ResourceManager.GetString("Valuacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 331.
        /// </summary>
        internal static string ValuacionIndividual {
            get {
                return ResourceManager.GetString("ValuacionIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 332.
        /// </summary>
        internal static string ValuacionMasiva {
            get {
                return ResourceManager.GetString("ValuacionMasiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.
        /// </summary>
        internal static string VIR {
            get {
                return ResourceManager.GetString("VIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 268.
        /// </summary>
        internal static string VisaulizarRegistros {
            get {
                return ResourceManager.GetString("VisaulizarRegistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 618.
        /// </summary>
        internal static string VisualizacionDDJJ {
            get {
                return ResourceManager.GetString("VisualizacionDDJJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 323.
        /// </summary>
        internal static string VisualizarABMExpedienteObra {
            get {
                return ResourceManager.GetString("VisualizarABMExpedienteObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 238.
        /// </summary>
        internal static string VisualizarActas {
            get {
                return ResourceManager.GetString("VisualizarActas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 212.
        /// </summary>
        internal static string VisualizarCertificados {
            get {
                return ResourceManager.GetString("VisualizarCertificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        internal static string VisualizarDesignaciones {
            get {
                return ResourceManager.GetString("VisualizarDesignaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 263.
        /// </summary>
        internal static string VisualizarDocumentos {
            get {
                return ResourceManager.GetString("VisualizarDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 251.
        /// </summary>
        internal static string VisualizarDomicilio {
            get {
                return ResourceManager.GetString("VisualizarDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string VisualizarExpedienteObra {
            get {
                return ResourceManager.GetString("VisualizarExpedienteObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        internal static string VisualizarInformeEstadistico {
            get {
                return ResourceManager.GetString("VisualizarInformeEstadistico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29.
        /// </summary>
        internal static string VisualizarInformeSeguimiento {
            get {
                return ResourceManager.GetString("VisualizarInformeSeguimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 226.
        /// </summary>
        internal static string VisualizarInspeccion {
            get {
                return ResourceManager.GetString("VisualizarInspeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 230.
        /// </summary>
        internal static string Visualizarinspectores {
            get {
                return ResourceManager.GetString("Visualizarinspectores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string VisualizarLiquidaciones {
            get {
                return ResourceManager.GetString("VisualizarLiquidaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 318.
        /// </summary>
        internal static string VisualizarMantenedor {
            get {
                return ResourceManager.GetString("VisualizarMantenedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23.
        /// </summary>
        internal static string VisualizarObservaciones {
            get {
                return ResourceManager.GetString("VisualizarObservaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 245.
        /// </summary>
        internal static string Visualizarpersona {
            get {
                return ResourceManager.GetString("Visualizarpersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string VisualizarPlanos {
            get {
                return ResourceManager.GetString("VisualizarPlanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 258.
        /// </summary>
        internal static string VisualizarProfesion {
            get {
                return ResourceManager.GetString("VisualizarProfesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27.
        /// </summary>
        internal static string VisualizarSuperficies {
            get {
                return ResourceManager.GetString("VisualizarSuperficies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 217.
        /// </summary>
        internal static string VisualizarTramites {
            get {
                return ResourceManager.GetString("VisualizarTramites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 319.
        /// </summary>
        internal static string VisualizarValuacion {
            get {
                return ResourceManager.GetString("VisualizarValuacion", resourceCulture);
            }
        }
    }
}
