//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoSit.Data.BusinessEntities.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Entradas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Entradas() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoSit.Data.BusinessEntities.GlobalResources.Entradas", typeof(Entradas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 12.
        /// </summary>
        public static string ComprobantePago {
            get {
                return ResourceManager.GetString("ComprobantePago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 6.
        /// </summary>
        public static string DDJJ {
            get {
                return ResourceManager.GetString("DDJJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 5.
        /// </summary>
        public static string DescripcionInmueble {
            get {
                return ResourceManager.GetString("DescripcionInmueble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 13.
        /// </summary>
        public static string EspacioPublico {
            get {
                return ResourceManager.GetString("EspacioPublico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 10.
        /// </summary>
        public static string LibreDeuda {
            get {
                return ResourceManager.GetString("LibreDeuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 7.
        /// </summary>
        public static string Manzana {
            get {
                return ResourceManager.GetString("Manzana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4.
        /// </summary>
        public static string MensuraRegistrada {
            get {
                return ResourceManager.GetString("MensuraRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2.
        /// </summary>
        public static string Parcela {
            get {
                return ResourceManager.GetString("Parcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 8.
        /// </summary>
        public static string Persona {
            get {
                return ResourceManager.GetString("Persona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 11.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3.
        /// </summary>
        public static string UnidadTributaria {
            get {
                return ResourceManager.GetString("UnidadTributaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 9.
        /// </summary>
        public static string Via {
            get {
                return ResourceManager.GetString("Via", resourceCulture);
            }
        }
    }
}
