//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoSit.Data.BusinessEntities.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ObjetosTramites {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ObjetosTramites() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoSit.Data.BusinessEntities.GlobalResources.ObjetosTramites", typeof(ObjetosTramites).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 55.
        /// </summary>
        public static string BajaMensura {
            get {
                return ResourceManager.GetString("BajaMensura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35.
        /// </summary>
        public static string CertificadoCatastral {
            get {
                return ResourceManager.GetString("CertificadoCatastral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 36.
        /// </summary>
        public static string CertificadoValuatorio {
            get {
                return ResourceManager.GetString("CertificadoValuatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48.
        /// </summary>
        public static string CertificadoValuatorioHistorico {
            get {
                return ResourceManager.GetString("CertificadoValuatorioHistorico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        public static string CopiasCertificadas {
            get {
                return ResourceManager.GetString("CopiasCertificadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 49.
        /// </summary>
        public static string CopiasSimples {
            get {
                return ResourceManager.GetString("CopiasSimples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60.
        /// </summary>
        public static string DivisionEdificacionAConstruirRegimenPreHorizontalidadMensuraRegistrada {
            get {
                return ResourceManager.GetString("DivisionEdificacionAConstruirRegimenPreHorizontalidadMensuraRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 62.
        /// </summary>
        public static string DivisionEdificacionExistenteAConstruirRegimenPHMensuraRegistrada {
            get {
                return ResourceManager.GetString("DivisionEdificacionExistenteAConstruirRegimenPHMensuraRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 61.
        /// </summary>
        public static string DivisionEdificacionExistenteRegimenPHMensuraRegistrada {
            get {
                return ResourceManager.GetString("DivisionEdificacionExistenteRegimenPHMensuraRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 37.
        /// </summary>
        public static string DivisionMensuraRegistrada {
            get {
                return ResourceManager.GetString("DivisionMensuraRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 85.
        /// </summary>
        public static string DivisionPrescripcionAdquisitivaMensuraRegistrada {
            get {
                return ResourceManager.GetString("DivisionPrescripcionAdquisitivaMensuraRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 56.
        /// </summary>
        public static string DivisionRegimenConjuntoInmobiliarioCementerioPrivadoMensuraRegistrada {
            get {
                return ResourceManager.GetString("DivisionRegimenConjuntoInmobiliarioCementerioPrivadoMensuraRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 57.
        /// </summary>
        public static string DivisionRegimenConjuntoInmobiliarioMensuraRegistrada {
            get {
                return ResourceManager.GetString("DivisionRegimenConjuntoInmobiliarioMensuraRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 65.
        /// </summary>
        public static string FraccionExtensionMayorRegimenDerechoRealSuperficie {
            get {
                return ResourceManager.GetString("FraccionExtensionMayorRegimenDerechoRealSuperficie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 51.
        /// </summary>
        public static string InformeBienesRegistrados {
            get {
                return ResourceManager.GetString("InformeBienesRegistrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 53.
        /// </summary>
        public static string InformeFotogrametrico {
            get {
                return ResourceManager.GetString("InformeFotogrametrico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 52.
        /// </summary>
        public static string InformeSituacionPartidaInmobiliaria {
            get {
                return ResourceManager.GetString("InformeSituacionPartidaInmobiliaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 59.
        /// </summary>
        public static string Mensura {
            get {
                return ResourceManager.GetString("Mensura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 72.
        /// </summary>
        public static string MensuraProyectoUnificacionYRedistribucionParcelaria {
            get {
                return ResourceManager.GetString("MensuraProyectoUnificacionYRedistribucionParcelaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 86.
        /// </summary>
        public static string MensuraServidumbre {
            get {
                return ResourceManager.GetString("MensuraServidumbre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 73.
        /// </summary>
        public static string MensuraUnificacionYRedistribucionParcelaria {
            get {
                return ResourceManager.GetString("MensuraUnificacionYRedistribucionParcelaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 67.
        /// </summary>
        public static string MensuraYDeslinde {
            get {
                return ResourceManager.GetString("MensuraYDeslinde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 68.
        /// </summary>
        public static string MensuraYDivision {
            get {
                return ResourceManager.GetString("MensuraYDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 58.
        /// </summary>
        public static string MensuraYDivisionRegimenConjuntoInmobiliario {
            get {
                return ResourceManager.GetString("MensuraYDivisionRegimenConjuntoInmobiliario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 69.
        /// </summary>
        public static string MensuraYDivisionRegimenConjuntoInmobiliarioCementerioPrivado {
            get {
                return ResourceManager.GetString("MensuraYDivisionRegimenConjuntoInmobiliarioCementerioPrivado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string MensuraYDivisionUrbana {
            get {
                return ResourceManager.GetString("MensuraYDivisionUrbana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 70.
        /// </summary>
        public static string MensuraYProyectoUnificacion {
            get {
                return ResourceManager.GetString("MensuraYProyectoUnificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 71.
        /// </summary>
        public static string MensuraYUnificacion {
            get {
                return ResourceManager.GetString("MensuraYUnificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 63.
        /// </summary>
        public static string ModificacionEdificacionExistenteRegimenPHMensuraRegistrada {
            get {
                return ResourceManager.GetString("ModificacionEdificacionExistenteRegimenPHMensuraRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 74.
        /// </summary>
        public static string ModificacionEstadoParcelarioMensuraRegistrada {
            get {
                return ResourceManager.GetString("ModificacionEstadoParcelarioMensuraRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 54.
        /// </summary>
        public static string OficiosInformes {
            get {
                return ResourceManager.GetString("OficiosInformes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64.
        /// </summary>
        public static string ParcelaPlanoRegistrado {
            get {
                return ResourceManager.GetString("ParcelaPlanoRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38.
        /// </summary>
        public static string PrescripcionAdquisitiva {
            get {
                return ResourceManager.GetString("PrescripcionAdquisitiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 66.
        /// </summary>
        public static string PrescripcionAdquisitivaDivision {
            get {
                return ResourceManager.GetString("PrescripcionAdquisitivaDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75.
        /// </summary>
        public static string ProyectoUnificacionMensuraRegistrada {
            get {
                return ResourceManager.GetString("ProyectoUnificacionMensuraRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 76.
        /// </summary>
        public static string ProyectoUnificacionYRedistribucionParcelariaMensuraRegistrada {
            get {
                return ResourceManager.GetString("ProyectoUnificacionYRedistribucionParcelariaMensuraRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 77.
        /// </summary>
        public static string RectificacionMensura {
            get {
                return ResourceManager.GetString("RectificacionMensura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 78.
        /// </summary>
        public static string UnificacionMensuraRegistrada {
            get {
                return ResourceManager.GetString("UnificacionMensuraRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 79.
        /// </summary>
        public static string UnificacionYRedistribucionParcelariaMensuraRegistrada {
            get {
                return ResourceManager.GetString("UnificacionYRedistribucionParcelariaMensuraRegistrada", resourceCulture);
            }
        }
    }
}
