//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoSit.Data.BusinessEntities.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TiposMensuras {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TiposMensuras() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoSit.Data.BusinessEntities.GlobalResources.TiposMensuras", typeof(TiposMensuras).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string Mensura {
            get {
                return ResourceManager.GetString("Mensura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        public static string MensuraDivisionConjuntoInmobiliarioCementerioPrivadoMensuraRegistrada {
            get {
                return ResourceManager.GetString("MensuraDivisionConjuntoInmobiliarioCementerioPrivadoMensuraRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        public static string MensuraDivisionConjuntosInmobiliariosMensuraRegistrada {
            get {
                return ResourceManager.GetString("MensuraDivisionConjuntosInmobiliariosMensuraRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        public static string MensuraDivisionEdificacionAConstruirRegimenPreHorizontalidadMensuraRegistrada {
            get {
                return ResourceManager.GetString("MensuraDivisionEdificacionAConstruirRegimenPreHorizontalidadMensuraRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        public static string MensuraDivisionEdificacionExistenteAConstruirRegimenPHMensuraRegistrada {
            get {
                return ResourceManager.GetString("MensuraDivisionEdificacionExistenteAConstruirRegimenPHMensuraRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        public static string MensuraDivisionEdificacionExistenteRegimenPHMensuraRegistrada {
            get {
                return ResourceManager.GetString("MensuraDivisionEdificacionExistenteRegimenPHMensuraRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        public static string MensuraDivisionMensuraRegistrada {
            get {
                return ResourceManager.GetString("MensuraDivisionMensuraRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string MensuraDivisionPrescripcionAdquisitivaMensuraRegistrada {
            get {
                return ResourceManager.GetString("MensuraDivisionPrescripcionAdquisitivaMensuraRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        public static string MensuraFraccionExtensionMayorRegimenDerechoRealSuperficie {
            get {
                return ResourceManager.GetString("MensuraFraccionExtensionMayorRegimenDerechoRealSuperficie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        public static string MensuraModificacionEdificacionExistenteRegimenPHMensuraRegistrada {
            get {
                return ResourceManager.GetString("MensuraModificacionEdificacionExistenteRegimenPHMensuraRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        public static string MensuraModificacionEstadoParcelarioMensuraRegistrada {
            get {
                return ResourceManager.GetString("MensuraModificacionEstadoParcelarioMensuraRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        public static string MensuraParcelaPlanoRegistrado {
            get {
                return ResourceManager.GetString("MensuraParcelaPlanoRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string MensuraPrescripcionAdquisitiva {
            get {
                return ResourceManager.GetString("MensuraPrescripcionAdquisitiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string MensuraPrescripcionAdquisitivaYDivision {
            get {
                return ResourceManager.GetString("MensuraPrescripcionAdquisitivaYDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.
        /// </summary>
        public static string MensuraProyectoUnificacionMensuraRegistrada {
            get {
                return ResourceManager.GetString("MensuraProyectoUnificacionMensuraRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string MensuraProyectoUnificacionYRedistribucionParcelaria {
            get {
                return ResourceManager.GetString("MensuraProyectoUnificacionYRedistribucionParcelaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19.
        /// </summary>
        public static string MensuraProyectoUnificacionYRedistribucionParcelariaMensuraRegistrada {
            get {
                return ResourceManager.GetString("MensuraProyectoUnificacionYRedistribucionParcelariaMensuraRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23.
        /// </summary>
        public static string MensuraRectificacion {
            get {
                return ResourceManager.GetString("MensuraRectificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        public static string MensuraServidumbre {
            get {
                return ResourceManager.GetString("MensuraServidumbre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99.
        /// </summary>
        public static string MensuraSinIdentificar {
            get {
                return ResourceManager.GetString("MensuraSinIdentificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        public static string MensuraUnificacionMensuraRegistrada {
            get {
                return ResourceManager.GetString("MensuraUnificacionMensuraRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string MensuraUnificacionYRedistribucionParcelaria {
            get {
                return ResourceManager.GetString("MensuraUnificacionYRedistribucionParcelaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17.
        /// </summary>
        public static string MensuraUnificacionYRedistribucionParcelariaMensuraRegistrada {
            get {
                return ResourceManager.GetString("MensuraUnificacionYRedistribucionParcelariaMensuraRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string MensuraYDeslinde {
            get {
                return ResourceManager.GetString("MensuraYDeslinde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string MensuraYDivision {
            get {
                return ResourceManager.GetString("MensuraYDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27.
        /// </summary>
        public static string MensuraYDivisionRegimenConjuntoInmobiliario {
            get {
                return ResourceManager.GetString("MensuraYDivisionRegimenConjuntoInmobiliario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26.
        /// </summary>
        public static string MensuraYDivisionRegimenConjuntoInmobiliarioCementerioPrivado {
            get {
                return ResourceManager.GetString("MensuraYDivisionRegimenConjuntoInmobiliarioCementerioPrivado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        public static string MensuraYProyectoUnificacion {
            get {
                return ResourceManager.GetString("MensuraYProyectoUnificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string MensuraYUnificacion {
            get {
                return ResourceManager.GetString("MensuraYUnificacion", resourceCulture);
            }
        }
    }
}
